trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
    allowUnstable: true
    addToPath: true
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

##- script: |
  ##  python -m unittest discover
  ##displayName: 'Run tests'

- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/app
    zip -r $(Build.ArtifactStagingDirectory)/app.zip . -x "*.git*"
  displayName: 'Package application'

- publish: $(Build.ArtifactStagingDirectory)/app.zip
  artifact: drop

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'My_Azure_Subscription'
    appName: 'python-web-app'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
  displayName: 'Deploy to Azure Web App'
